version: 0.1
log:
  level: debug
storage:
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: 0.0.0.0:5000
    secret: asecretforlocaldevelopment
    debug:
        addr: localhost:5001
notifications:
  endpoints:
    - name: alistener
      disabled: false
      url: http://10.189.98.235:8080
      timeout: 500
      threshold: 5
      backoff: 1000
      ignoredmediatypes:
        - application/octet-stream
